### ISSUE TITLE
Geass or not geass

### ISSUE THREAD

**Issue by Pafzedog** [crazy-max/geass#2]
Salut,

peut-on encore espérer  voir aboutir ce fabuleux projet ?

bye :)

**Comment by crazy-max** [comment]
Salut oui c'est toujours dans les cartons mais je n'ai pas beaucoup de temps pour avancer :(
Un jour ou l'autre ça sortira du grenier ;)

**Comment by Pafzedog** [comment]
ok, bonne nouvelle alors :)
merci de ta réponse. 
à+
